#!/usr/bin/perl

# $RCSfile: ADB,v $$Revision: 1.1.1.1 $$Date: 1998/08/12 17:33:00 $

# This script is only useful when used in your crash directory.

$num = shift;
exec 'adb', '-k', "vmunix.$num", "vmcore.$num";
